name: installer
description: "A small tool to easily update your modpacks."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+100070

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  archive: ^4.0.7
  background_downloader: ^9.2.2
  basics: ^0.10.0
  flutter_confetti: ^0.5.1
  gpt_markdown: ^1.0.19
  handy_window: ^0.4.0
  nes_ui: ^0.24.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  stow_plain: ^0.5.1
  yaru: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  golden_screenshot: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Monocraft.license

  fonts:
    - family: Monocraft
      fonts:
        - asset: assets/fonts/Monocraft.ttc

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon.png"
  windows:
    generate: true
    icon_size: 256
