name: installer
description: "A small tool to easily update your modpacks."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.4+100040

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  archive: ^4.0.7
  background_downloader: ^9.2.2
  basics: ^0.10.0
  flutter_confetti: ^0.5.1
  gpt_markdown: ^1.0.19
  handy_window: ^0.4.0
  nes_ui: ^0.24.0
  path: ^1.9.1
  path_provider: ^2.1.5
  stow_plain: ^0.5.1
  yaru: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Monocraft.license

  fonts:
    - family: Monocraft
      fonts:
        - asset: assets/fonts/Monocraft.ttc

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon.png"
  windows:
    generate: true
    icon_size: 256
