name: Build for Linux

on:
  workflow_dispatch:
  push:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install apt dependencies
        run:
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa \
            clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      - name: Install dependencies
        run: flutter pub get

      - name: Disable Flutter CLI animations
        run: flutter config --no-cli-animations

      - run: flutter pub get

      - name: Build Linux
        run: flutter build linux
      
      - name: Compress build
        id: compress
        run: |
          mkdir -p AppDir
          mv build/linux/x64/release/bundle/* AppDir
          chmod +x AppDir/installer
          tar -C AppDir -cvf modpack_installer.tar.gz .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: modpack_installer-linux-bin
          path: modpack_installer.tar.gz

  build-appimage:
    name: Build AppImage
    needs: build-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AppImage dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2

      - name: Download app archive
        uses: actions/download-artifact@v4
        with:
          name: modpack_installer-linux-bin

      - name: Download appimage-builder
        working-directory: appimage
        run: |
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage

      - name: Prepare build files
        working-directory: appimage
        run: |
          mkdir AppDir
          tar -xvf ../modpack_installer.tar.gz -C AppDir

      - name: Build AppImage
        working-directory: appimage
        run: |
          ./appimage-builder-x86_64.AppImage --skip-test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage artifact
          path: appimage/modpack_installer-*-x86_64.AppImage*

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: appimage/modpack_installer-*-x86_64.AppImage*
          file_glob: true
