name: Build for Windows

on:
  workflow_dispatch:
  push:

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      - name: Disable Flutter CLI animations
        run: flutter config --no-cli-animations

      - run: flutter pub get

      - name: Build Windows
        run: flutter build windows

      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/

      - name: Copy build output
        run: |
          mkdir package
          xcopy /E /I /Y build\windows\x64\runner\Release\* package\

      - name: Create 7z archive
        run: |
          & "C:\Program Files\7-Zip\7z.exe" a -r app.7z .\package\*

      - name: Create final SFX executable
        shell: cmd
        run: |
          copy /b "C:\Program Files\7-Zip\7zS.sfx" + windows/config.txt + app.7z modpack_installer.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: modpack_installer_portable
          path: modpack_installer.exe

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: modpack_installer.exe
