name: Build for Windows

on:
  workflow_dispatch:
  push:

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      - name: Disable Flutter CLI animations
        run: flutter config --no-cli-animations

      - run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - name: Set installer version
        shell: bash
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 1)
          sed -i "s/#define MyAppVersion \".*\"/#define MyAppVersion \"$VERSION\"/" windows/inno.iss

      - name: Remove cruft
        working-directory: build\windows\x64\runner\Release
        shell: bash
        run: |
          rm data/flutter_assets/packages/flutter_math_fork/lib/katex_fonts/fonts/*.ttf
          rm data/flutter_assets/packages/gpt_markdown/lib/fonts/*.ttf
          rm data/flutter_assets/packages/nes_ui/google_fonts/*.ttf
          truncate -s 0 data/flutter_assets/packages/nes_ui/google_fonts/OFL.txt
          rm data/flutter_assets/packages/yaru/assets/fonts/*.ttf

      - name: Install Inno Setup
        run: choco install -y innosetup

      - name: Build Windows Installer
        run: ISCC.exe windows\inno.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: windows/modpack_installer_installer.exe

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: windows/modpack_installer_installer.exe
