name: Build for Windows

on:
  workflow_dispatch:
  push:

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      - name: Disable Flutter CLI animations
        run: flutter config --no-cli-animations

      - run: flutter pub get

      - name: Build Windows
        run: flutter build windows

      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/
      
      - name: Zip Windows build artifacts
        run: |
          Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath modpack_installer_windows.zip -CompressionLevel Optimal

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: modpack_installer_windows.zip
